name: bootstrap_sass
version: 4.6.0
description: Sass source files to create Bootstrap themes for Dart Web.
homepage: https://github.com/luisvt/bootstrap_sass

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  sass_builder: ^2.2.1
  build_runner: any
  build_test: any
  build_web_compilers: any
  lints: ^2.0.1
